# Generated by Django 4.2.30 on 2026-08-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='conversions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
