# Generated by Django 4.2.30 on 2026-09-09 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_engine', '0004_product_affiliate_link_product_image_product_likes_and_more'),
        ('analytics', '0003_analytics_conversions_analytics_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='product_engine.product'),
        ),
    ]
