# Generated by Django 4.2.30 on 2026-06-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engine_content', to='product_engine.product'),
        ),
    ]
