# Generated by Django 4.2.30 on 2026-09-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_engine', '0004_product_affiliate_link_product_image_product_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
