# Generated by Django 4.2.30 on 2026-09-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_engine', '0005_alter_favorite_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
