# Generated by Django 4.2.30 on 2026-09-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_engine', '0006_product_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('Amazon', 'Amazon'), ('AliExpress', 'AliExpress'), ('eBay', 'eBay'), ('Etsy', 'Etsy')], default='Amazon', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
