# Generated by Django 4.2.30 on 2026-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_engine', '0007_product_platform_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='affiliate_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
