# Generated by Django 4.2.30 on 2026-09-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_engine', '0008_alter_product_affiliate_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='aliexpress_id',
        ),
        migrations.AddField(
            model_name='product',
            name='ebay_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='etsy_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
