# Generated by Django 4.2.30 on 2026-08-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trends', '0002_trend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('affiliate_url', models.URLField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.trend')),
            ],
        ),
    ]
