# Generated by Django 4.2.30 on 2026-08-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_trend'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Content', 'verbose_name_plural': 'AI Contents'},
        ),
        migrations.AddField(
            model_name='content',
            name='trend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trends.trend'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['product'], name='ai_content_product_0eaf3f_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['trend'], name='ai_content_trend_i_351467_idx'),
        ),
    ]
